#!/usr/bin/env python
"""
Script to clean-up tmux sessions
"""

import boto3
import time
import sys
import os

def run_shell(cmd):
  """Runs shell command, returns list of outputted lines
  with newlines stripped"""
  #  print(cmd)
  p = Popen(cmd, shell=True, stdout=PIPE, stderr=STDOUT)
  (stdout, stderr) = p.communicate()
  lines = stdout.split('\n')
  stripped_lines = []
  for l in lines:
    stripped_line = l.strip()
    if l:
      stripped_lines.append(stripped_line)
  return stripped_lines

from subprocess import PIPE, STDOUT, Popen

def run_shell(cmd):
  """Runs shell command, returns list of outputted lines
  with newlines stripped"""
  #  print(cmd)
  p = Popen(cmd, shell=True, stdout=PIPE, stderr=STDOUT)
  (stdout, stderr) = p.communicate()
  stdout = stdout.decode('ascii')
  lines = stdout.split('\n')
  stripped_lines = []
  for l in lines:
    stripped_line = l.strip()
    if l:
      stripped_lines.append(stripped_line)
  return stripped_lines

def main():
  for line in run_shell('tmux ls'):
    session_name = line.split(':', 1)[0]
    
    if session_name == 'tensorboard' or session_name == 'jupyter':
      print("Skipping "+session_name)
      continue
    print("Killing "+session_name)
    run_shell('tmux kill-session -t ' + session_name)

if __name__=='__main__':
  main()
